language: cpp
sudo: required
dist: trusty

# Notes:
# $HOME -> /home/travis
# code checked out to (this is $PWD for the script) -> /home/travis/build/kinetictheory/gsl

env:
  global:
    - DISTRO=trusty
    - CCACHE_CPP2=yes
    - GCCVER=7
    - CC=gcc-${GCCVER}
    - CXX=g++-${GCCVER}
    - FC=gfortran-${GCCVER}
    - VENDOR_DIR=$HOME/vendors
    - CMAKE_VER=3.9.0-Linux-x86_64
    - CMAKE=$VENDOR_DIR/cmake-${CMAKE_VER}/bin/cmake
    - CTEST=$VENDOR_DIR/cmake-${CMAKE_VER}/bin/ctest
    - OMP_NUM_THREADS=4
    - COVERAGE=ON

matrix:
    - WERROR=ON
#    - STYLE=ON

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-7
      - g++-7
      - gfortran-7

before_install:
  - mkdir -p ${VENDOR_DIR}/bin & export PATH=${VENDOR_DIR}/bin:$PATH
  - export PATH=${PATH}:${VENDOR_DIR}/cmake-${CMAKE_VER}/bin
  - pip install --upgrade --user pip
  - if [[ ${COVERAGE}  ]]; then pip install --user codecov; fi

install:
  - cd $VENDOR_DIR
  - wget -q --no-check-certificate http://www.cmake.org/files/v${CMAKE_VER:0:3}/cmake-${CMAKE_VER}.tar.gz
  - tar -xzf cmake-${CMAKE_VER}.tar.gz &> expand-cmake.log

before_script:
  - if [[ ${WERROR} ]]; then for i in CC CXX Fortran; do eval export ${i}_FLAGS=\"-Werror\"; done; fi
  - if [[ ${COVERAGE} ]]; then for i in CC CXX Fortran; do eval export ${i}_FLAGS+=\" --coverage\"; done; fi

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install ..
  - cmake --build . --target install
  - ctest -j 2 --output-on-failure

after_success:
  - if [[ ${COVERAGE} ]]; then codecov --gcov-exec gcov-${GCCVER}; fi

cache:
  - ccache

compiler:
  - gcc-7

git:
  depth: 3
